version: "3.7"
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  tech-test:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nginx
    ports:
      - "80:80"
